// background.js
// this list has 1000 most common german words where the even index(starting from zero 0) is german, and the next corresponding odd index is english
let germanWordList = ["German","English",
"wie","as",
"ich","I",
"seine","his",
"dass","that",
"er","he",
"war","was",
"für","for",
"auf","on",
"sind","are",
"mit","with",
"sie","they",
"sein","be",
"bei","at",
"ein","one",
"haben","have",
"dies","this",
"aus","from",
"durch","by",
"heiß","hot",
"Wort","word",
"aber","but",
"was","what",
"einige","some",
"ist","is",
"es","it",
"Sie","you",
"oder","or",
"hatte","had",
"die","the",
"von","of",
"zu","to",
"und","and",
"ein","a",
"bei","in",
"wir","we",
"können","can",
"aus","out",
"andere","other",
"waren","were",
"die","which",
"tun","do",
"ihre","their",
"Zeit","time",
"wenn","if",
"werden","will",
"wie","how",
"sagte","said",
"ein","an",
"jeder","each",
"sagen","tell",
"tut","does",
"Satz","set",
"drei","three",
"wollen","want",
"Luft","air",
"gut","well",
"auch","also",
"spielen","play",
"klein","small",
"Ende","end",
"setzen","put",
"Zuhause","home",
"lesen","read",
"seits","hand",
"Hafen","port",
"groß","large",
"buchstabieren","spell",
"hinzufügen","add",
"auch","even",
"Lande","land",
"hier","here",
"muss","must",
"groß","big",
"hoch","high",
"so","such",
"folgen","follow",
"Akt","act",
"warum","why",
"fragen","ask",
"Männer","men",
"Veränderung","change",
"ging","went",
"Licht","light",
"Art","kind",
"aus","off",
"müssen","need",
"Haus","house",
"Bild","picture",
"versuchen","try",
"uns","us",
"wieder","again",
"Tier","animal",
"Punkt","point",
"Mutter","mother",
"Welt","world",
"in der Nähe von","near",
"bauen","build",
"selbst","self",
"Erde","earth",
"Vater","father",
"jeder","any",
"neu","new",
"Arbeit","work",
"Teil","part",
"nehmen","take",
"erhalten","get",
"Ort","place",
"gemacht","made",
"leben","live",
"wo","where",
"nach","after",
"zurück","back",
"wenig","little",
"nur","only",
"Runde","round",
"Mann","man",
"Jahr","year",
"kam","came",
"zeigen","show",
"jeder","every",
"gut","good",
"mir","me",
"geben","give",
"unsere","our",
"unter","under",
"Name","name",
"sehr","very",
"durch","through",
"nur","just",
"Formular","form",
"Satz","sentence",
"groß","great",
"denken","think",
"sagen","say",
"Hilfe","help",
"niedrig","low",
"Linie","line",
"abweichen","differ",
"wiederum","turn",
"Ursache","cause",
"viel","much",
"bedeuten","mean",
"vor","before",
"Umzug","move",
"Recht","right",
"Junge","boy",
"alt","old",
"zu","too",
"gleich","same",
"sie","she",
"alle","all",
"da","there",
"wenn","when",
"nach oben","up",
"Verwendung","use",
"Ihre","your",
"Weg","way",
"über","about",
"viele","many",
"dann","then",
"sie","them",
"schreiben","write",
"würde","would",
"wie","like",
"so","so",
"diese","these",
"sie","her",
"lange","long",
"machen","make",
"Sache","thing",
"sehen","see",
"ihm","him",
"zwei","two",
"hat","has",
"suchen","look",
"mehr","more",
"Tag","day",
"könnte","could",
"gehen","go",
"kommen","come",
"tat","did",
"Anzahl","number",
"klingen","sound",
"nicht","no",
"am meisten","most",
"Menschen","people",
"meine","my",
"über","over",
"wissen","know",
"Wasser","water",
"als","than",
"Anruf","call",
"erste","first",
"die","who",
"können","may",
"nach unten","down",
"Seite","side",
"gewesen","been",
"jetzt","now",
"finden","find",
"Kopf","head",
"stehen","stand",
"besitzen","own",
"Seite","page",
"sollte","should",
"Land","country",
"gefunden","found",
"Antwort","answer",
"Schule","school",
"wachsen","grow",
"Studie","study",
"noch","still",
"lernen","learn",
"Anlage","plant",
"Abdeckung","cover",
"Lebensmittel","food",
"Sonne","sun",
"vier","four",
"zwischen","between",
"Zustand","state",
"halten","keep",
"Auge","eye",
"nie","never",
"letzte","last",
"lassen","let",
"Gedanken","thought",
"Stadt","city",
"Baum","tree",
"überqueren","cross",
"Bauernhof","farm",
"schwer","hard",
"Beginn","start",
"Macht","might",
"Geschichte","story",
"Säge","saw",
"weit","far",
"Meer","sea",
"ziehen","draw",
"links","left",
"spät","late",
"laufen","run",
"unterlassen Sie","don’t",
"während","while",
"Presse","press",
"Schließen","close",
"Nacht","night",
"realen","real",
"Leben","life",
"wenige","few",
"Norden","north",
"Buch","book",
"tragen","carry",
"nahm","took",
"Wissenschaft","science",
"essen","eat",
"Zimmer","room",
"Freund","friend",
"begann","began",
"Idee","idea",
"Fisch","fish",
"berg","mountain",
"Stopp","stop",
"einmal","once",
"Basis","base",
"hören","hear",
"Pferd","horse",
"Schnitt","cut",
"sicher","sure",
"beobachten","watch",
"Farbe","color",
"Gesicht","face",
"Holz","wood",
"Haupt-","main",
"geöffnet","open",
"scheinen","seem",
"zusammen","together",
"nächste","next",
"weiß","white",
"Kinder","children",
"Start","begin",
"bekam","got",
"gehen","walk",
"Beispiel","example",
"erleichtern","ease",
"Papier","paper",
"Gruppe","group",
"immer","always",
"Musik","music",
"diejenigen","those",
"beide","both",
"Marke","mark",
"oft","often",
"Schreiben","letter",
"bis","until",
"Meile","mile",
"Fluss","river",
"Auto","car",
"Füße","feet",
"Pflege","care",
"zweite","second",
"genug","enough",
"Ebene","plain",
"Mädchen","girl",
"üblich","usual",
"jung","young",
"bereit","ready",
"oben","above",
"je","ever",
"rot","red",
"Liste","list",
"obwohl","though",
"fühlen","feel",
"Vortrag","talk",
"Vogel","bird",
"bald","soon",
"Körper","body",
"Hund","dog",
"Familie","family",
"direkt","direct",
"Pose","pose",
"verlassen","leave",
"Lied","song",
"messen","measure",
"Tür","door",
"Produkt","product",
"schwarz","black",
"kurz","short",
"Zahl","numeral",
"Klasse","class",
"Wind","wind",
"Frage","question",
"passieren","happen",
"vollständig","complete",
"Schiff","ship",
"Bereich","area",
"Hälfte","half",
"Stein","rock",
"bestellen","order",
"Feuer","fire",
"Süden","south",
"Problem","problem",
"Stück","piece",
"sagte","told",
"wusste","knew",
"passieren","pass",
"seit","since",
"obere","top",
"ganze","whole",
"König","king",
"Straße","street",
"Zoll","inch",
"multiplizieren","multiply",
"nichts","nothing",
"Kurs","course",
"bleiben","stay",
"Rad","wheel",
"voll","full",
"Kraft","force",
"blau","blue",
"Objekt","object",
"entscheiden","decide",
"Oberfläche","surface",
"tief","deep",
"Mond","moon",
"Insel","island",
"Fuß","foot",
"System","system",
"beschäftigt","busy",
"Prüfung","test",
"Rekord","record",
"Boot","boat",
"gemeinsam","common",
"goldenen","gold",
"möglich","possible",
"Flugzeug","plane",
"statt","stead",
"trocken","dry",
"Wunder","wonder",
"Lachen","laugh",
"tausend","thousand",
"vor","ago",
"lief","ran",
"überprüfen","check",
"Spiel","game",
"Form","shape",
"gleichsetzen","equate",
"heiß","hot",
"Fehl","miss",
"gebracht","brought",
"Wärme","heat",
"Schnee","snow",
"Reifen","tire",
"bringen","bring",
"ja","yes",
"entfernt","distant",
"füllen","fill",
"Osten","east",
"malen","paint",
"Sprache","language",
"unter","among",
"Einheit","unit",
"Macht","power",
"Stadt","town",
"fein","fine",
"sicher","certain",
"fliegen","fly",
"fallen","fall",
"führen","lead",
"Schrei","cry",
"dunkel","dark",
"Maschine","machine",
"note","note",
"warten","wait",
"Plan","plan",
"Abbildung","figure",
"Stern","star",
"Kasten","box",
"Nomen","noun",
"Feld","field",
"Rest","rest",
"richtig","correct",
"fähig","able",
"Pfund","pound",
"getan","done",
"Schönheit","beauty",
"Antriebs","drive",
"stand","stood",
"enthalten","contain",
"Front","front",
"lehren","teach",
"Woche","week",
"Finale","final",
"gab","gave",
"grün","green",
"oh","oh",
"schnell","quick",
"entwickeln","develop",
"Ozean","ocean",
"warme","warm",
"kostenlos","free",
"Minute","minute",
"stark","strong",
"besondere","special",
"Geist","mind",
"hinter","behind",
"klar","clear",
"Schwanz","tail",
"produzieren","produce",
"Tatsache","fact",
"Raum","space",
"gehört","heard",
"beste","best",
"Stunde","hour",
"besser","better",
"wahr","TRUE",
"während","during",
"hundert","hundred",
"fünf","five",
"merken","remember",
"Schritt","step",
"früh","early",
"halten","hold",
"Westen","west",
"Boden","ground",
"Interesse","interest",
"erreichen","reach",
"schnell","fast",
"Verbum","verb",
"singen","sing",
"hören","listen",
"sechs","six",
"Tabelle","table",
"Reise","travel",
"weniger","less",
"Morgen","morning",
"zehn","ten",
"einfach","simple",
"mehrere","several",
"Vokal","vowel",
"auf","toward",
"Krieg","war",
"legen","lay",
"gegen","against",
"Muster","pattern",
"schleppend","slow",
"Zentrum","center",
"Liebe","love",
"Person","person",
"Geld","money",
"dienen","serve",
"erscheinen","appear",
"Straße","road",
"Karte","map",
"regen","rain",
"Regel","rule",
"regieren","govern",
"ziehen","pull",
"Kälte","cold",
"Hinweis","notice",
"Stimme","voice",
"Energie","energy",
"Jagd","hunt",
"wahrscheinlich","probable",
"Bett","bed",
"Bruder","brother",
"Ei","egg",
"Fahrt","ride",
"Zelle","cell",
"glauben","believe",
"vielleicht","perhaps",
"pflücken","pick",
"plötzlich","sudden",
"zählen","count",
"Platz","square",
"Grund","reason",
"Dauer","length",
"vertreten","represent",
"Kunst","art",
"Thema","subject",
"Region","region",
"Größe","size",
"variieren","vary",
"regeln","settle",
"sprechen","speak",
"Gewicht","weight",
"allgemein","general",
"Eis","ice",
"Materie","matter",
"Kreis","circle",
"Paar","pair",
"umfassen","include",
"Kluft","divide",
"Silbe","syllable",
"Filz","felt",
"groß","grand",
"Kugel","ball",
"noch","yet",
"Welle","wave",
"fallen","drop",
"Herz","heart",
"Uhr","am",
"vorhanden","present",
"schwer","heavy",
"Tanz","dance",
"Motor","engine",
"Position","position",
"Arm","arm",
"breit","wide",
"Segel","sail",
"Material","material",
"Fraktion","fraction",
"Wald","forest",
"sitzen","sit",
"Rennen","race",
"Fenster","window",
"Speicher","store",
"Sommer","summer",
"Zug","train",
"Schlaf","sleep",
"beweisen","prove",
"einsam","lone",
"Bein","leg",
"Übung","exercise",
"Wand","wall",
"Fang","catch",
"Berg","mount",
"wünschen","wish",
"Himmel","sky",
"Board","board",
"Freude","joy",
"Winter","winter",
"sa","sat",
"geschrieben","written",
"wilden","wild",
"Instrument","instrument",
"gehalten","kept",
"Glas","glass",
"Gras","grass",
"Kuh","cow",
"Arbeit","job",
"Rand","edge",
"Zeichen","sign",
"Besuch","visit",
"Vergangenheit","past",
"weich","soft",
"Spaß","fun",
"hell","bright",
"Gases","gas",
"Wetter","weather",
"Monat","month",
"Million","million",
"tragen","bear",
"Finish","finish",
"glücklich","happy",
"hoffen","hope",
"blume","flower",
"kleiden","clothe",
"seltsam","strange",
"Vorbei","gone",
"Handel","trade",
"Melodie","melody",
"Reise","trip",
"Büro","office",
"empfangen","receive",
"Reihe","row",
"Mund","mouth",
"genau","exact",
"Zeichen","symbol",
"sterben","die",
"am wenigsten","least",
"Ärger","trouble",
"Schrei","shout",
"außer","except",
"schrieb","wrote",
"Samen","seed",
"Ton","tone",
"beitreten","join",
"vorschlagen","suggest",
"sauber","clean",
"Pause","break",
"Dame","lady",
"Hof","yard",
"steigen","rise",
"schlecht","bad",
"Schlag","blow",
"Öl","oil",
"Blut","blood",
"berühren","touch",
"wuchs","grew",
"Cent","cent",
"mischen","mix",
"Mannschaft","team",
"Draht","wire",
"Kosten","cost",
"verloren","lost",
"braun","brown",
"tragen","wear",
"Garten","garden",
"gleich","equal",
"gesendet","sent",
"wählen","choose",
"fiel","fell",
"passen","fit",
"fließen","flow",
"Messe","fair",
"Bank","bank",
"sammeln","collect",
"sparen","save",
"Kontrolle","control",
"dezimal","decimal",
"Ohr","ear",
"sonst","else",
"ganz","quite",
"pleite","broke",
"Fall","case",
"Mitte","middle",
"töten","kill",
"Sohn","son",
"See","lake",
"Moment","moment",
"Maßstab","scale",
"laut","loud",
"Frühling","spring",
"beobachten","observe",
"Kind","child",
"gerade","straight",
"Konsonant","consonant",
"Nation","nation",
"Wörterbuch","dictionary",
"milch","milk",
"Geschwindigkeit","speed",
"Verfahren","method",
"Orgel","organ",
"zahlen","pay",
"Alter","age",
"Abschnitt","section",
"Kleid","dress",
"Wolke","cloud",
"Überraschung","surprise",
"ruhig","quiet",
"Stein","stone",
"winzig","tiny",
"Aufstieg","climb",
"kühlen","cool",
"Entwurf","design",
"arm","poor",
"Menge","lot",
"Versuch","experiment",
"Boden","bottom",
"Schlüssel","key",
"Eisen","iron",
"Einzel","single",
"Stick","stick",
"Wohnung","flat",
"zwanzig","twenty",
"Haut","skin",
"Lächeln","smile",
"Falte","crease",
"Loch","hole",
"springen","jump",
"Kind","baby",
"acht","eight",
"Dorf","village",
"treffen","meet",
"Wurzel","root",
"kaufen","buy",
"erhöhen","raise",
"lösen","solve",
"Metall","metal",
"ob","whether",
"drücken","push",
"sieben","seven",
"Absatz","paragraph",
"dritte","third",
"wird","shall",
"Hand","held",
"Haar","hair",
"beschreiben","describe",
"Koch","cook",
"Boden","floor",
"entweder","either",
"Ergebnis","result",
"brennen","burn",
"Hügel","hill",
"sicher","safe",
"Katze","cat",
"Jahrhundert","century",
"betrachten","consider",
"Typ","type",
"Gesetz","law",
"Bit","bit",
"Küste","coast",
"Kopie","copy",
"Ausdruck","phrase",
"still","silent",
"hoch","tall",
"Sand","sand",
"Boden","soil",
"Rolle","roll",
"Temperatur","temperature",
"Finger","finger",
"Industrie","industry",
"Wert","value",
"Kampf","fight",
"Lüge","lie",
"schlagen","beat",
"begeistern","excite",
"natürlich","natural",
"Blick","view",
"Sinn","sense",
"Hauptstadt","capital",
"wird nicht","won’t",
"Stuhl","chair",
"Achtung","danger",
"Obst","fruit",
"reich","rich",
"dick","thick",
"Soldat","soldier",
"Prozess","process",
"betreiben","operate",
"Praxis","practice",
"trennen","separate",
"schwierig","difficult",
"Arzt","doctor",
"Bitte","please",
"schützen","protect",
"Mittag","noon",
"Ernte","crop",
"modernen","modern",
"Elementes","element",
"treffen","hit",
"Schüler","student",
"Ecke","corner",
"Partei","party",
"Versorgung","supply",
"deren","whose",
"lokalisieren","locate",
"Rings","ring",
"Charakter","character",
"insekt","insect",
"gefangen","caught",
"Zeit","period",
"zeigen","indicate",
"Funk","radio",
"Speiche","spoke",
"Atom","atom",
"Mensch","human",
"Geschichte","history",
"Wirkung","effect",
"elektrisch","electric",
"erwarten","expect",
"Knochen","bone",
"Schiene","rail",
"vorstellen","imagine",
"bieten","provide",
"zustimmen","agree",
"so","thus",
"sanft","gentle",
"Frau","woman",
"Kapitän","captain",
"erraten","guess",
"erforderlich","necessary",
"scharf","sharp",
"Flügel","wing",
"schaffen","create",
"Nachbar","neighbor",
"Wasch","wash",
"Fledermaus","bat",
"eher","rather",
"Menge","crowd",
"mais","corn",
"vergleichen","compare",
"Gedicht","poem",
"Schnur","string",
"Glocke","bell",
"abhängen","depend",
"Fleisch","meat",
"einreiben","rub",
"Rohr","tube",
"berühmt","famous",
"Dollar","dollar",
"Strom","stream",
"Angst","fear",
"Blick","sight",
"dünn","thin",
"Dreieck","triangle",
"Erde","planet",
"Eile","hurry",
"Chef","chief",
"Kolonie","colony",
"Uhr","clock",
"Mine","mine",
"Krawatte","tie",
"eingeben","enter",
"Dur","major",
"frisch","fresh",
"Suche","search",
"senden","send",
"gelb","yellow",
"Pistole","gun",
"erlauben","allow",
"Druck","print",
"tot","dead",
"Stelle","spot",
"Wüste","desert",
"Anzug","suit",
"Strom","current",
"Aufzug","lift",
"stiegen","rose",
"ankommen","arrive",
"Stamm","master",
"Spur","track",
"Elternteil","parent",
"Ufer","shore",
"Teilung","division",
"Blatt","sheet",
"Substanz","substance",
"begünstigen","favor",
"verbinden","connect",
"nach","post",
"verbringen","spend",
"Akkord","chord",
"Fett","fat",
"froh","glad",
"Original","original",
"Aktie","share",
"Station","station",
"Papa","dad",
"Brot","bread",
"aufladen","charge",
"richtig","proper",
"Leiste","bar",
"Angebot","offer",
"Segment","segment",
"Sklave","slave",
"ente","duck",
"Augenblick","instant",
"Markt","market",
"Grad","degree",
"besiedeln","populate",
"küken","chick",
"liebe","dear",
"Feind","enemy",
"antworten","reply",
"Getränk","drink",
"auftreten","occur",
"Unterstützung","support",
"Rede","speech",
"Natur","nature",
"Angebot","range",
"Dampf","steam",
"Bewegung","motion",
"Weg","path",
"Flüssigkeit","liquid",
"protokollieren","log",
"gemeint","meant",
"Quotient","quotient",
"Gebiss","teeth",
"Schale","shell",
"Hals","neck",
"Sauerstoff","oxygen",
"Zucker","sugar",
"Tod","death",
"ziemlich","pretty",
"Geschicklichkeit","skill",
"Frauen","women",
"Saison","season",
"Lösung","solution",
"Magnet","magnet",
"Silber","silver",
"danken","thank",
"Zweig","branch",
"Spiel","match",
"Suffix","suffix",
"insbesondere","especially",
"Feige","fig",
"ängstlich","afraid",
"riesig","huge",
"Schwester","sister",
"Stahl","steel",
"diskutieren","discuss",
"vorwärts","forward",
"ähnlich","similar",
"führen","guide",
"Erfahrung","experience",
"Partitur","score",
"apfel","apple",
"gekauft","bought",
"geführt","led",
"Tonhöhe","pitch",
"Mantel","coat",
"Masse","mass",
"Karte","card",
"Band","band",
"Seil","rope",
"Rutsch","slip",
"gewinnen","win",
"träumen","dream",
"Abend","evening",
"Zustand","condition",
"Futtermittel","feed",
"Werkzeug","tool",
"gesamt","total",
"Basis","basic",
"Geruch","smell",
"Tal","valley",
"noch","nor",
"doppelt","double",
"Sitz","seat",
"fortsetzen","continue",
"Block","block",
"Tabelle","chart",
"Hut","hat",
"verkaufen","sell",
"Erfolg","success",
"Firma","company",
"subtrahieren","subtract",
"Veranstaltung","event",
"besondere","particular",
"viel","deal",
"schwimmen","swim",
"Begriff","term",
"Gegenteil","opposite",
"Frau","wife",
"Schuh","shoe",
"Schulter","shoulder",
"Verbreitung","spread",
"arrangieren","arrange",
"Lager","camp",
"erfinden","invent",
"Baumwolle","cotton",
"geboren","born",
"bestimmen","determine",
"Quart","quart",
"neun","nine",
"Lastwagen","truck",
"Lärm","noise",
"Ebene","level",
"Chance","chance",
"sammeln","gather",
"Geschäft","shop",
"Stretch","stretch",
"werfen","throw",
"Glanz","shine",
"Immobilien","property",
"Spalte","column",
"Molekül","molecule",
"wählen","select",
"falsch","wrong",
"grau","gray",
"Wiederholung","repeat",
"erfordern","require",
"breit","broad",
"vorbereiten","prepare",
"Salz","salt",
"Nase","nose",
"mehreren","plural",
"Zorn","anger",
"Anspruch","claim",
"Kontinent","continent"]

let germanWordListObject = {"german":"english","wie":"like","ich":"i","seine":"his","dass":"that","er":"he","war":"was","für":"for","auf":"toward","sind":"are","mit":"with","sie":"her","sein":"be","bei":"in","ein":"an","haben":"have","dies":"this","aus":"off","durch":"through","heiß":"hot","wort":"word","aber":"but","was":"what","einige":"some","ist":"is","es":"it","oder":"or","hatte":"had","die":"who","von":"of","zu":"too","und":"and","wir":"we","können":"may","andere":"other","waren":"were","tun":"do","ihre":"your","zeit":"period","wenn":"when","werden":"will","sagte":"told","jeder":"every","sagen":"say","tut":"does","satz":"sentence","drei":"three","wollen":"want","luft":"air","gut":"good","auch":"even","spielen":"play","klein":"small","ende":"end","setzen":"put","zuhause":"home","lesen":"read","seits":"hand","hafen":"port","groß":"grand","buchstabieren":"spell","hinzufügen":"add","lande":"land","hier":"here","muss":"must","hoch":"tall","so":"thus","folgen":"follow","akt":"act","warum":"why","fragen":"ask","männer":"men","veränderung":"change","ging":"went","licht":"light","art":"kind","müssen":"need","haus":"house","bild":"picture","versuchen":"try","uns":"us","wieder":"again","tier":"animal","punkt":"point","mutter":"mother","welt":"world","in der nähe von":"near","bauen":"build","selbst":"self","erde":"planet","vater":"father","neu":"new","arbeit":"job","teil":"part","nehmen":"take","erhalten":"get","ort":"place","gemacht":"made","leben":"life","wo":"where","nach":"post","zurück":"back","wenig":"little","nur":"just","runde":"round","mann":"man","jahr":"year","kam":"came","zeigen":"indicate","mir":"me","geben":"give","unsere":"our","unter":"among","name":"name","sehr":"very","formular":"form","denken":"think","hilfe":"help","niedrig":"low","linie":"line","abweichen":"differ","wiederum":"turn","ursache":"cause","viel":"deal","bedeuten":"mean","vor":"ago","umzug":"move","recht":"right","junge":"boy","alt":"old","gleich":"equal","alle":"all","da":"there","nach oben":"up","verwendung":"use","weg":"path","über":"over","viele":"many","dann":"then","schreiben":"letter","würde":"would","diese":"these","lange":"long","machen":"make","sache":"thing","sehen":"see","ihm":"him","zwei":"two","hat":"has","suchen":"look","mehr":"more","tag":"day","könnte":"could","gehen":"walk","kommen":"come","tat":"did","anzahl":"number","klingen":"sound","nicht":"no","am meisten":"most","menschen":"people","meine":"my","wissen":"know","wasser":"water","als":"than","anruf":"call","erste":"first","nach unten":"down","seite":"page","gewesen":"been","jetzt":"now","finden":"find","kopf":"head","stehen":"stand","besitzen":"own","sollte":"should","land":"country","gefunden":"found","antwort":"answer","schule":"school","wachsen":"grow","studie":"study","noch":"nor","lernen":"learn","anlage":"plant","abdeckung":"cover","lebensmittel":"food","sonne":"sun","vier":"four","zwischen":"between","zustand":"condition","halten":"hold","auge":"eye","nie":"never","letzte":"last","lassen":"let","gedanken":"thought","stadt":"town","baum":"tree","überqueren":"cross","bauernhof":"farm","schwer":"heavy","beginn":"start","macht":"power","geschichte":"history","säge":"saw","weit":"far","meer":"sea","ziehen":"pull","links":"left","spät":"late","laufen":"run","unterlassen sie":"don’t","während":"during","presse":"press","schließen":"close","nacht":"night","realen":"real","wenige":"few","norden":"north","buch":"book","tragen":"wear","nahm":"took","wissenschaft":"science","essen":"eat","zimmer":"room","freund":"friend","begann":"began","idee":"idea","fisch":"fish","berg":"mount","stopp":"stop","einmal":"once","basis":"basic","hören":"listen","pferd":"horse","schnitt":"cut","sicher":"safe","beobachten":"observe","farbe":"color","gesicht":"face","holz":"wood","haupt-":"main","geöffnet":"open","scheinen":"seem","zusammen":"together","nächste":"next","weiß":"white","kinder":"children","start":"begin","bekam":"got","beispiel":"example","erleichtern":"ease","papier":"paper","gruppe":"group","immer":"always","musik":"music","diejenigen":"those","beide":"both","marke":"mark","oft":"often","bis":"until","meile":"mile","fluss":"river","auto":"car","füße":"feet","pflege":"care","zweite":"second","genug":"enough","ebene":"level","mädchen":"girl","üblich":"usual","jung":"young","bereit":"ready","oben":"above","je":"ever","rot":"red","liste":"list","obwohl":"though","fühlen":"feel","vortrag":"talk","vogel":"bird","bald":"soon","körper":"body","hund":"dog","familie":"family","direkt":"direct","pose":"pose","verlassen":"leave","lied":"song","messen":"measure","tür":"door","produkt":"product","schwarz":"black","kurz":"short","zahl":"numeral","klasse":"class","wind":"wind","frage":"question","passieren":"pass","vollständig":"complete","schiff":"ship","bereich":"area","hälfte":"half","stein":"stone","bestellen":"order","feuer":"fire","süden":"south","problem":"problem","stück":"piece","wusste":"knew","seit":"since","obere":"top","ganze":"whole","könig":"king","straße":"road","zoll":"inch","multiplizieren":"multiply","nichts":"nothing","kurs":"course","bleiben":"stay","rad":"wheel","voll":"full","kraft":"force","blau":"blue","objekt":"object","entscheiden":"decide","oberfläche":"surface","tief":"deep","mond":"moon","insel":"island","fuß":"foot","system":"system","beschäftigt":"busy","prüfung":"test","rekord":"record","boot":"boat","gemeinsam":"common","goldenen":"gold","möglich":"possible","flugzeug":"plane","statt":"stead","trocken":"dry","wunder":"wonder","lachen":"laugh","tausend":"thousand","lief":"ran","überprüfen":"check","spiel":"match","form":"shape","gleichsetzen":"equate","fehl":"miss","gebracht":"brought","wärme":"heat","schnee":"snow","reifen":"tire","bringen":"bring","ja":"yes","entfernt":"distant","füllen":"fill","osten":"east","malen":"paint","sprache":"language","einheit":"unit","fein":"fine","fliegen":"fly","fallen":"drop","führen":"guide","schrei":"shout","dunkel":"dark","maschine":"machine","note":"note","warten":"wait","plan":"plan","abbildung":"figure","stern":"star","kasten":"box","nomen":"noun","feld":"field","rest":"rest","richtig":"proper","fähig":"able","pfund":"pound","getan":"done","schönheit":"beauty","antriebs":"drive","stand":"stood","enthalten":"contain","front":"front","lehren":"teach","woche":"week","finale":"final","gab":"gave","grün":"green","oh":"oh","schnell":"fast","entwickeln":"develop","ozean":"ocean","warme":"warm","kostenlos":"free","minute":"minute","stark":"strong","besondere":"particular","geist":"mind","hinter":"behind","klar":"clear","schwanz":"tail","produzieren":"produce","tatsache":"fact","raum":"space","gehört":"heard","beste":"best","stunde":"hour","besser":"better","wahr":"true","hundert":"hundred","fünf":"five","merken":"remember","schritt":"step","früh":"early","westen":"west","boden":"soil","interesse":"interest","erreichen":"reach","verbum":"verb","singen":"sing","sechs":"six","tabelle":"chart","reise":"trip","weniger":"less","morgen":"morning","zehn":"ten","einfach":"simple","mehrere":"several","vokal":"vowel","krieg":"war","legen":"lay","gegen":"against","muster":"pattern","schleppend":"slow","zentrum":"center","liebe":"dear","person":"person","geld":"money","dienen":"serve","erscheinen":"appear","karte":"card","regen":"rain","regel":"rule","regieren":"govern","kälte":"cold","hinweis":"notice","stimme":"voice","energie":"energy","jagd":"hunt","wahrscheinlich":"probable","bett":"bed","bruder":"brother","ei":"egg","fahrt":"ride","zelle":"cell","glauben":"believe","vielleicht":"perhaps","pflücken":"pick","plötzlich":"sudden","zählen":"count","platz":"square","grund":"reason","dauer":"length","vertreten":"represent","kunst":"art","thema":"subject","region":"region","größe":"size","variieren":"vary","regeln":"settle","sprechen":"speak","gewicht":"weight","allgemein":"general","eis":"ice","materie":"matter","kreis":"circle","paar":"pair","umfassen":"include","kluft":"divide","silbe":"syllable","filz":"felt","kugel":"ball","welle":"wave","herz":"heart","uhr":"clock","vorhanden":"present","tanz":"dance","motor":"engine","position":"position","arm":"poor","breit":"broad","segel":"sail","material":"material","fraktion":"fraction","wald":"forest","sitzen":"sit","rennen":"race","fenster":"window","speicher":"store","sommer":"summer","zug":"train","schlaf":"sleep","beweisen":"prove","einsam":"lone","bein":"leg","übung":"exercise","wand":"wall","fang":"catch","wünschen":"wish","himmel":"sky","board":"board","freude":"joy","winter":"winter","sa":"sat","geschrieben":"written","wilden":"wild","instrument":"instrument","gehalten":"kept","glas":"glass","gras":"grass","kuh":"cow","rand":"edge","zeichen":"symbol","besuch":"visit","vergangenheit":"past","weich":"soft","spaß":"fun","hell":"bright","gases":"gas","wetter":"weather","monat":"month","million":"million","finish":"finish","glücklich":"happy","hoffen":"hope","blume":"flower","kleiden":"clothe","seltsam":"strange","vorbei":"gone","handel":"trade","melodie":"melody","büro":"office","empfangen":"receive","reihe":"row","mund":"mouth","genau":"exact","sterben":"die","am wenigsten":"least","ärger":"trouble","außer":"except","schrieb":"wrote","samen":"seed","ton":"tone","beitreten":"join","vorschlagen":"suggest","sauber":"clean","pause":"break","dame":"lady","hof":"yard","steigen":"rise","schlecht":"bad","schlag":"blow","öl":"oil","blut":"blood","berühren":"touch","wuchs":"grew","cent":"cent","mischen":"mix","mannschaft":"team","draht":"wire","kosten":"cost","verloren":"lost","braun":"brown","garten":"garden","gesendet":"sent","wählen":"select","fiel":"fell","passen":"fit","fließen":"flow","messe":"fair","bank":"bank","sammeln":"gather","sparen":"save","kontrolle":"control","dezimal":"decimal","ohr":"ear","sonst":"else","ganz":"quite","pleite":"broke","fall":"case","mitte":"middle","töten":"kill","sohn":"son","see":"lake","moment":"moment","maßstab":"scale","laut":"loud","frühling":"spring","kind":"baby","gerade":"straight","konsonant":"consonant","nation":"nation","wörterbuch":"dictionary","milch":"milk","geschwindigkeit":"speed","verfahren":"method","orgel":"organ","zahlen":"pay","alter":"age","abschnitt":"section","kleid":"dress","wolke":"cloud","überraschung":"surprise","ruhig":"quiet","winzig":"tiny","aufstieg":"climb","kühlen":"cool","entwurf":"design","menge":"crowd","versuch":"experiment","schlüssel":"key","eisen":"iron","einzel":"single","stick":"stick","wohnung":"flat","zwanzig":"twenty","haut":"skin","lächeln":"smile","falte":"crease","loch":"hole","springen":"jump","acht":"eight","dorf":"village","treffen":"hit","wurzel":"root","kaufen":"buy","erhöhen":"raise","lösen":"solve","metall":"metal","ob":"whether","drücken":"push","sieben":"seven","absatz":"paragraph","dritte":"third","wird":"shall","hand":"held","haar":"hair","beschreiben":"describe","koch":"cook","entweder":"either","ergebnis":"result","brennen":"burn","hügel":"hill","katze":"cat","jahrhundert":"century","betrachten":"consider","typ":"type","gesetz":"law","bit":"bit","küste":"coast","kopie":"copy","ausdruck":"phrase","still":"silent","sand":"sand","rolle":"roll","temperatur":"temperature","finger":"finger","industrie":"industry","wert":"value","kampf":"fight","lüge":"lie","schlagen":"beat","begeistern":"excite","natürlich":"natural","blick":"sight","sinn":"sense","hauptstadt":"capital","wird nicht":"won’t","stuhl":"chair","achtung":"danger","obst":"fruit","reich":"rich","dick":"thick","soldat":"soldier","prozess":"process","betreiben":"operate","praxis":"practice","trennen":"separate","schwierig":"difficult","arzt":"doctor","bitte":"please","schützen":"protect","mittag":"noon","ernte":"crop","modernen":"modern","elementes":"element","schüler":"student","ecke":"corner","partei":"party","versorgung":"supply","deren":"whose","lokalisieren":"locate","rings":"ring","charakter":"character","insekt":"insect","gefangen":"caught","funk":"radio","speiche":"spoke","atom":"atom","mensch":"human","wirkung":"effect","elektrisch":"electric","erwarten":"expect","knochen":"bone","schiene":"rail","vorstellen":"imagine","bieten":"provide","zustimmen":"agree","sanft":"gentle","frau":"wife","kapitän":"captain","erraten":"guess","erforderlich":"necessary","scharf":"sharp","flügel":"wing","schaffen":"create","nachbar":"neighbor","wasch":"wash","fledermaus":"bat","eher":"rather","mais":"corn","vergleichen":"compare","gedicht":"poem","schnur":"string","glocke":"bell","abhängen":"depend","fleisch":"meat","einreiben":"rub","rohr":"tube","berühmt":"famous","dollar":"dollar","strom":"current","angst":"fear","dünn":"thin","dreieck":"triangle","eile":"hurry","chef":"chief","kolonie":"colony","mine":"mine","krawatte":"tie","eingeben":"enter","dur":"major","frisch":"fresh","suche":"search","senden":"send","gelb":"yellow","pistole":"gun","erlauben":"allow","druck":"print","tot":"dead","stelle":"spot","wüste":"desert","anzug":"suit","aufzug":"lift","stiegen":"rose","ankommen":"arrive","stamm":"master","spur":"track","elternteil":"parent","ufer":"shore","teilung":"division","blatt":"sheet","substanz":"substance","begünstigen":"favor","verbinden":"connect","verbringen":"spend","akkord":"chord","fett":"fat","froh":"glad","original":"original","aktie":"share","station":"station","papa":"dad","brot":"bread","aufladen":"charge","leiste":"bar","angebot":"range","segment":"segment","sklave":"slave","ente":"duck","augenblick":"instant","markt":"market","grad":"degree","besiedeln":"populate","küken":"chick","feind":"enemy","antworten":"reply","getränk":"drink","auftreten":"occur","unterstützung":"support","rede":"speech","natur":"nature","dampf":"steam","bewegung":"motion","flüssigkeit":"liquid","protokollieren":"log","gemeint":"meant","quotient":"quotient","gebiss":"teeth","schale":"shell","hals":"neck","sauerstoff":"oxygen","zucker":"sugar","tod":"death","ziemlich":"pretty","geschicklichkeit":"skill","frauen":"women","saison":"season","lösung":"solution","magnet":"magnet","silber":"silver","danken":"thank","zweig":"branch","suffix":"suffix","insbesondere":"especially","feige":"fig","ängstlich":"afraid","riesig":"huge","schwester":"sister","stahl":"steel","diskutieren":"discuss","vorwärts":"forward","ähnlich":"similar","erfahrung":"experience","partitur":"score","apfel":"apple","gekauft":"bought","geführt":"led","tonhöhe":"pitch","mantel":"coat","masse":"mass","band":"band","seil":"rope","rutsch":"slip","gewinnen":"win","träumen":"dream","abend":"evening","futtermittel":"feed","werkzeug":"tool","gesamt":"total","geruch":"smell","tal":"valley","doppelt":"double","sitz":"seat","fortsetzen":"continue","block":"block","hut":"hat","verkaufen":"sell","erfolg":"success","firma":"company","subtrahieren":"subtract","veranstaltung":"event","schwimmen":"swim","begriff":"term","gegenteil":"opposite","schuh":"shoe","schulter":"shoulder","verbreitung":"spread","arrangieren":"arrange","lager":"camp","erfinden":"invent","baumwolle":"cotton","geboren":"born","bestimmen":"determine","quart":"quart","neun":"nine","lastwagen":"truck","lärm":"noise","chance":"chance","geschäft":"shop","stretch":"stretch","werfen":"throw","glanz":"shine","immobilien":"property","spalte":"column","molekül":"molecule","falsch":"wrong","grau":"gray","wiederholung":"repeat","erfordern":"require","vorbereiten":"prepare","salz":"salt","nase":"nose","mehreren":"plural","zorn":"anger","anspruch":"claim","kontinent":"continent"}

let processedList = {}

// it will extract unique words from an array or string
function extractUniqueWords(input) {
    let words;
    
    if (typeof input === 'string') {
      words = input.toLowerCase().split(/\W+/);
    } else if (Array.isArray(input)) {
      words = input.map(item => item.toLowerCase());
    } else {
      throw new Error('Input must be a string or an array.');
    }
    
    const uniqueWords = [...new Set(words)];
    return uniqueWords;
  }

// it will replace words you want to replace with new words preserving case.
function replaceWord(sentence, oldWord, newWord) {
    // Create a regular expression that matches the old word surrounded by word boundaries
    var regex = new RegExp("\\b" + oldWord + "\\b", "gi");
    
    // Function to preserve the case of the original word
    var replacer = function(match) {
      if (match === oldWord) {
        return newWord;
      } else if (match === oldWord.charAt(0).toUpperCase() + oldWord.slice(1)) {
        return newWord.charAt(0).toUpperCase() + newWord.slice(1);
      } else {
        return newWord.toLowerCase();
      }
    };
    
    // Use the replace method with the regex and replacer function to replace all instances of the old word
    var newSentence = sentence.replace(regex, replacer);
    
    return newSentence;
   }
   

// this function replace whitespace with underscores of a sentence
function replaceSpacesWithUnderscores(sentence) {
  return sentence.replace(/[^a-zA-Z0-9\u00C0-\u00FF]/g, '_');
}


// as directly modifying the captions has its drawbacks,  the same translated captions are fetched and sent to background for translation again, to prevent this, we are keeping a record
function checkProcessedList(sentence){
    if(processedList[replaceSpacesWithUnderscores(sentence)] || Object.values(processedList).includes(sentence)){
        console.log('found in processedlist')
        return sentence
    } else {
        let wordsToFind = extractWords(sentence)
        let newSentence = findGermanMeaning(wordsToFind, sentence)
        processedList[replaceSpacesWithUnderscores(sentence)] = newSentence
        console.log(processedList)
        return newSentence
    }
}

// this function would extract words only out of a string, while excluding all special characters and spaces and return them as an array
function extractWords(str) {
    // Remove special characters and numbers
    const cleanedStr = str.replace(/[^\p{L}\s]/gu, '');
  
    // Split the cleaned string into an array of words
    const words = cleanedStr.split(/\s+/).filter(word => word !== '');
  
    return extractUniqueWords(words);
  }


//   here the parameter is an array which the words that need to be translated and the german word list
// function findGermanMeaning(wordsToFind, rawSentence){
//     let translatedSentence = rawSentence
//     // make it efficient
//     console.log(wordsToFind, ': total words to find.')
//     wordsToFind.forEach((word)=>{
//         if(germanWordList.includes(word.toLowerCase())){
//             // every time the raw sentence is getting output
//                 translatedSentence = replaceWord(translatedSentence, word, `${word}(${germanWordList[germanWordList.indexOf(word.toLowerCase())+1]})`)
//                 console.log(`${word} exists: ${translatedSentence}`, translatedSentence, word)            
//             } else{
//                 console.log(`${word} doesn't exists.`)
//             }
//     })

//     return translatedSentence.trim()   
// }

//   here the parameter is an array which the words that need to be translated and the german word list
function findGermanMeaning(wordsToFind, rawSentence){
    let translatedSentence = rawSentence
    // make it efficient
    console.log(wordsToFind, ': total words to find.')
    wordsToFind.forEach((word)=>{
        if(!!(germanWordListObject[word.toLowerCase()])){
            // every time the raw sentence is getting output
                translatedSentence = replaceWord(translatedSentence, word, `${word}(${germanWordListObject[word.toLowerCase()]})`)
                console.log(`${word} exists: ${translatedSentence}`, translatedSentence, word)            
            } else{
                console.log(`${word} doesn't exists.`)
            }
    })

    return translatedSentence.trim()   
}


// listen for messages
chrome.runtime.onMessage.addListener((message, sender, sendResponse)=>{
    // From captionMonitorContentScript line: 45
    console.log(message.message.trim(), 'from background 1105 line')
    sendResponse({message: checkProcessedList(message.message.trim())})
})
